# Generated by Django 3.0.8 on 2020-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='show',
        ),
        migrations.AddField(
            model_name='article',
            name='hiden',
            field=models.BooleanField(default=False),
        ),
    ]
