# Generated by Django 3.0.8 on 2020-08-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200811_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uuid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
